### ISSUE TITLE
Python client too

### ISSUE THREAD

**Issue by keraton** [dlresende/extreme-carpaccio#23]
Hi diego, I would like to add python client server, can you add me as a contributor ?

**Comment by dlresende** [comment]
Hello @keraton, you can do it form now. You just need to fork the project, add the client and submit a pull request.
A Python client is a very good idea ;)

**Comment by dlresende** [comment]
A new python client was added thanks to @keraton.

I will still leave this issue opened to update the client with the new resource [/feedback](https://github.com/dlresende/extreme-carpaccio/blob/master/clients/java/java-httpserver/src/test/java/xcarpaccio/MyHttpServerTest.java). Actually we are trying to implement this resource in all client in such a way the server will be able to notify clients abount what is going on.

**Comment by vador** [comment]
I made a pull request
