### ISSUE TITLE
Chalk bump break imports

### ISSUE THREAD

**Issue by Cardiox12** [dlresende/extreme-carpaccio#362]
# Chalk bump break imports

Hello guys, I tried to run the server but got this error :

```sh
> extreme-carpaccio-server@1.0.0 start
> node bin/www

/private/tmp/extreme-carpaccio/server/javascripts/repositories.js:4
var chalk = require('chalk')
            ^

Error [ERR_REQUIRE_ESM]: require() of ES Module /private/tmp/extreme-carpaccio/server/node_modules/chalk/source/index.js from /private/tmp/extreme-carpaccio/server/javascripts/repositories.js not supported.
Instead change the require of index.js in /private/tmp/extreme-carpaccio/server/javascripts/repositories.js to a dynamic import() which is available in all CommonJS modules.
    at Object.<anonymous> (/private/tmp/extreme-carpaccio/server/javascripts/repositories.js:4:13) {
  code: 'ERR_REQUIRE_ESM'
}

Node.js v21.7.1
```

I tried with the following conditions :
- OS: MacOS Sonoma 14.1
- Node: v21.7.1

It seems that the culprit is the bump of `Chalk 4.1.2 -> Chalk 5.3.0`, when I checkout on commit [5859d8f80586cdde32f294e9cdf14ae9266a8470](https://github.com/dlresende/extreme-carpaccio/commit/fda6bff0d789edee6ebe9516c96d931bacd80156), it works.

Have a nice day. :)

**Comment by dlresende** [comment]
Thanks for raising an issue @Cardiox12

I created a PR with a temporary fix until we can deal with the `chalk` `v4` > `v5` migration.
