### ISSUE TITLE
Add wrong request to break participants clients

### ISSUE THREAD

**Issue by dlresende** [dlresende/extreme-carpaccio#53]
In order to encourage participants to test, it'd be great that the server starts sending bad requests. In order to not be charged with penalties, the participant should respond with the http code 400 to server. It'd be great if this feature could be activated on the fly with some frequency, like, for each 10 requests one request is wrong.

**Comment by Arnauld** [comment]
I'll take it; make you pushed to config management so that i can plug this behavior into it
