### ISSUE TITLE
Unstable server tests

### ISSUE THREAD

**Issue by jak78** [dlresende/extreme-carpaccio#77]
## Problem
Sometimes when I run `npm test` on the server, I get the following failure:
```
 1) BadRequest should randomly corrupt order
   Message:
     Expected { prices : [ 64.73, 29.48, 73.49, 58.88, 46.61, 65.4, 16.23 ], quantities : [ 3, 10, 6, 5, 9, 5 ], country : 'FR', reduction : 'STANDARD' } not to equal { prices : [ 64.73, 29.48, 73.49, 58.88, 46.61, 65.4, 16.23 ], quantities : [ 3, 10, 6, 5, 9, 5 ], country : 'FR', reduction : 'STANDARD' }.
   Stacktrace:
     Error: Expected { prices : [ 64.73, 29.48, 73.49, 58.88, 46.61, 65.4, 16.23 ], quantities : [ 3, 10, 6, 5, 9, 5 ], country : 'FR', reduction : 'STANDARD' } not to equal { prices : [ 64.73, 29.48, 73.49, 58.88, 46.61, 65.4, 16.23 ], quantities : [ 3, 10, 6, 5, 9, 5 ], country : 'FR', reduction : 'STANDARD' }.
```

Most often the test passes. But sometimes it fails randomly.

## How to reproduce the problem

Run the following script to be pretty sure to see the problem:

```bash
#!/usr/bin/env bash
set -e
for i in $(seq 1 100); do
	npm test
done
```

Tested on:
- macOS 10.12.4
- node v7.9.0

## Analysis

The test expects the random-generated order corruption to be different than the previous corrupted order. There is a non-null probability that the random order generator builds an identical corrupted order. 

## Suggestion

Maybe we could set the random generator seed, or mock the random. Which one do you prefer?
I'll try to make a PR.

**Comment by jak78** [comment]
The corrupt order test expects 2 successive corrupted orders to always be different. But the implementation does not guarantee it. So I considered 2 options:

1. make the test follow the implementation: stop expecting 2 successive corrupted orders to always be different
2. fix the implementation to guarantee 2 successive corrupted orders to be different

WDYT?

**Comment by dlresende** [comment]
Making the test follow the implementation was a good call.

Thanks a lot @jak78!
