### ISSUE TITLE
Reduction table

### ISSUE THREAD

**Issue by xereda** [dlresende/extreme-carpaccio#90]
Hi,

Where can I configure the reduction table? What are the standard options? Can I set it up?

A hug,

Jackson

**Comment by xereda** [comment]
@dlresende...

**Comment by dlresende** [comment]
Hi @xereda,

Sorry, I missed this issue...

If you want to change the reduction during the game, you need to change the [config file](https://github.com/dlresende/extreme-carpaccio/blob/29a9afc5da1a0925a20aa70caa36ad4e671d4699/server/configuration.json#L2).

The code is [here](https://github.com/dlresende/extreme-carpaccio/blob/master/server/javascripts/services/reduction.js#L22-L30).
